### ISSUE TITLE
A serious global change and an arguably bad dependency?

### ISSUE THREAD

**Issue by niruvt** [ezgranet/tramlines#1]
On [this](https://github.com/ezgranet/tramlines/blob/64cec7ea2193cbfdffbfba44d44f3dec88b92c83/tramlines/tramlines.sty#L31) line of your package, you seemingly make a global change that would affect the entire document and the tables apart from your requirement which might not be desirable to many users.

Another problem that probably would be undesirable to you yourself is that users can have `\setlength\doublerulesep{some-length}` in their documents and the effect desired by you is now changed.

```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tramlines}

\begin{document}
\tramlines{hello world}
\lipsum[1-1]
\setlength{\doublerulesep}{30pt}
\tramlines{hello world}
\lipsum[1-1]
\end{document}
```

**Comment by ezgranet** [comment]
Very good point. I'll change that to not make it global. No reason the package should affect anywhere else.

**Comment by ezgranet** [comment]
Ok, here's the new command, not global

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%
% tramlines
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newcommand{\tramlinesep}{2pt}
\newcommand{\tramlines}[1]{\normalsize
\smallskip
\begin{minipage}{\textwidth}
\centering
{%notglobal
\setlength\doublerulesep{\tramlinesep}% <-- set distance between double rule
\begin{tabular}[t]{l c c }
\toprule\toprule
 & #1 &  \\
\bottomrule\bottomrule
\end{tabular}}
\end{minipage}
\smallskip
}
```
