### ISSUE TITLE
Strange results because of LaTeX-`float`s.

### ISSUE THREAD

**Issue by niruvt** [ezgranet/tramlines#2]
Since you have used the `table*` environment which is a [LaTeX-`float`](https://tex.stackexchange.com/a/39020), the results can be rather strange and unexpected. E.g.,

```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tramlines}

\begin{document}
\lipsum[1-1]
\lipsum[1-1]
\lipsum[1-1]
\lipsum[1-1]
\tramlines{hello world}
\end{document}
```

Using a [`minipage`](http://latexref.xyz/minipage.html) containing a [`tikzpicture`](https://www.overleaf.com/learn/latex/TikZ_package) would be more correct IMO, but even better would be to modify sections with package [`titlesec`](https://www.overleaf.com/learn/latex/Sections_and_chapters#Customize_chapters_and_sections).

**Comment by ezgranet** [comment]
Good point: a minipage or some other float could work. `titlesec` is out though because a legal document has sections that are separate to tramlines (which are only used for the title).

**Comment by ezgranet** [comment]
Okay, re-defining it with `minipage` seems to work pretty well
